apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80  # port exposed on cloud loadbalancer
      targetPort: 8080  # pod port
  selector:
    app: simple-app  # should match with labels on pod